name: HealFeedCMD
main: BeeAZZ\HealFeedCMD\Main
api: 4.0.0
version: 0.2
author: BeeAZZ
commands:
  heal:
    description: "Healing"
    permission: heal.command
  feed:
    description: "Food Recovery"
    permission: feed.command
permissions:
 healfeedcmd.command.heal:
  default: op
 healfeedcmd.command.feed:
  default: op
